@FinanceHub.Api_HostAddress = http://localhost:5009

POST {{FinanceHub.Api_HostAddress}}/api/usuarios
Content-Type: application/json

{
  "nome": "Igor",
  "email": "igor@email.com",
  "senha": "123456"
}