@FinanceHub.Api_HostAddress = http://localhost:5009

### Buscar todos os usuários
GET {{FinanceHub.Api_HostAddress}}/api/usuarios

###

### Buscar usuário por ID
GET {{FinanceHub.Api_HostAddress}}/api/usuarios/01bba28f-ac4e-4a65-86e8-8c3c0ebc25f4

###

### Cadastrar usuário
POST {{FinanceHub.Api_HostAddress}}/api/usuarios
Content-Type: application/json

{
    "nome": "Igor",
    "email": "igor@email.com",
    "senha": "123456"
}

###

### Atualizar usuário

PUT {{FinanceHub.Api_HostAddress}}/api/usuarios/01bba28f-ac4e-4a65-86e8-8c3c0ebc25f4
Content-Type: application/json

{
    "nome": "",
    "email": "igor@email.com"
}

###