@FinanceHub.Api_HostAddress = http://localhost:5009

### Buscar todos os usuários
GET {{FinanceHub.Api_HostAddress}}/api/usuarios

###

### Buscar usuário por ID
GET {{FinanceHub.Api_HostAddress}}/api/usuarios/01bba28f-ac4e-4a65-86e8-8c3c0ebc25f4

###

### Cadastrar usuário
POST {{FinanceHub.Api_HostAddress}}/api/usuarios
Content-Type: application/json

{
    "nome": "Igor",
    "email": "igor@email.com",
    "senha": "123456"
}

###

### Atualizar usuário

PUT {{FinanceHub.Api_HostAddress}}/api/usuarios/01bba28f-ac4e-4a65-86e8-8c3c0ebc25f4
Content-Type: application/json

{
    "nome": "",
    "email": "igor@email.com"
}

###

### Desativar usuário
DELETE {{FinanceHub.Api_HostAddress}}/api/usuarios/11111111-1111-1111-1111-111111111111

###



### Buscar todas as bolsas

GET {{FinanceHub.Api_HostAddress}}/api/bolsas



### Criar Ativo

POST {{FinanceHub.Api_HostAddress}}/api/ativos
Content-Type: application/json

{
    "nome": "Itaú Unibanco",
    "ticker": "BBAS3",
    "tipo": 0,
    "bolsaId": "41111111-1111-1111-1111-111111111111"
}

###

### Buscar todos os ativos

GET {{FinanceHub.Api_HostAddress}}/api/ativos

###

### Buscar por Id

GET {{FinanceHub.Api_HostAddress}}/api/ativos/CE6C5F54-D039-4A73-8C75-08DEF4C7E5F5

###

### Atualizar

PUT {{FinanceHub.Api_HostAddress}}/api/ativos/CE6C5F54-D039-4A73-8C75-08DEF4C7E5F5
Content-Type: application/json

{
    "nome": "Itaú Unibanco Holding",
    "ticker": "ITUB4",
    "tipo": 0
}

###

### Desativar

DELETE {{FinanceHub.Api_HostAddress}}/api/ativos/CE6C5F54-D039-4A73-8C75-08DEF4C7E5F5

###

### Criar uma Carteira

POST {{FinanceHub.Api_HostAddress}}/api/carteiras
Content-Type: application/json

{
  "usuarioId": "D8478176-56DC-43F1-AE30-BF76369250F6",
  "nome": "Carteira Principal"
}

###

### Criar uma compra de um ativo

POST {{FinanceHub.Api_HostAddress}}/api/carteiras/comprar
Content-Type: application/json

{
    "carteiraId":"11111111-1111-1111-1111-111111111111",
    "ativoId":"CE6C5F54-D039-4A73-8C75-08DEF4C7E5F5",
    "quantidade":50,
    "preco":20
}

###

### Criar uma venda de um ativo

POST {{FinanceHub.Api_HostAddress}}/api/carteiras/vender
Content-Type: application/json

{
    "carteiraId":"542B2700-26EA-4778-B0D2-6C7A9E5671A6",
    "ativoId":"11111111-1111-1111-1111-111111111111",
    "quantidade":1,
    "preco":10
}

###