name: CI

on:
  push:
    branches:
      - main
      - ci/github-actions

  pull_request:
    branches:
      - main

jobs:

  build-and-test:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout
        uses: actions/checkout@v5

      # =========================================
      # .NET
      # =========================================

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      # =========================================
      # INFRASTRUCTURE
      # =========================================

      - name: Start infrastructure
        run: docker compose up -d --build

      - name: Show containers
        run: docker compose ps

      - name: Wait for SQL Server
        run: |
          for i in {1..30}; do
            if (echo > /dev/tcp/127.0.0.1/1433) >/dev/null 2>&1; then
              echo "SQL Server is accepting connections."
              exit 0
            fi

            echo "Waiting for SQL Server..."
            sleep 2
          done

          echo "SQL Server did not become available."
          docker compose logs sqlserver
          exit 1

      - name: Wait for Redis
        run: |
          for i in {1..30}; do
            if (echo > /dev/tcp/127.0.0.1/6379) >/dev/null 2>&1; then
              echo "Redis is accepting connections."
              exit 0
            fi

            echo "Waiting for Redis..."
            sleep 2
          done

          echo "Redis did not become available."
          docker compose logs redis
          exit 1

      - name: Wait for RabbitMQ
        run: |
          for i in {1..30}; do
            if (echo > /dev/tcp/127.0.0.1/5672) >/dev/null 2>&1; then
              echo "RabbitMQ is accepting connections."
              exit 0
            fi

            echo "Waiting for RabbitMQ..."
            sleep 2
          done

          echo "RabbitMQ did not become available."
          docker compose logs rabbitmq
          exit 1

      # =========================================
      # TESTS
      # =========================================

      - name: Test
        env:
          TEST_DATABASE_CONNECTION_STRING: "Server=localhost,1433;Database=FinanceHubTestDb;User Id=sa;Password=FinanceHub@123;TrustServerCertificate=True;"

          Redis__ConnectionString: "localhost:6379"

          RABBITMQ_HOST: "localhost"
          RABBITMQ_USERNAME: "guest"
          RABBITMQ_PASSWORD: "guest"

        run: dotnet test --no-build --configuration Release

      # =========================================
      # DEBUG
      # =========================================

      - name: Show logs on failure
        if: failure()
        run: docker compose logs

      # =========================================
      # DOCKER IMAGE
      # =========================================

      - name: Docker Build
        run: docker build -t financehub-api:ci -f Dockerfile .

      - name: Login to GHCR
        if: github.event_name == 'push'
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag Docker Image
        if: github.event_name == 'push'
        run: docker tag financehub-api:ci ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/financehub-api:${GITHUB_SHA}

      - name: Push Docker Image
        if: github.event_name == 'push'
        run: docker push ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/financehub-api:${GITHUB_SHA}


  # =========================================
  # DEPLOY
  # =========================================

  deploy:

    needs: build-and-test

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    steps:

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker Image
        run: docker pull ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/financehub-api:${GITHUB_SHA}

      - name: Run Docker Container
        run: |
          docker run -d \
            --name financehub-api \
            -p 8080:8080 \
            ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/financehub-api:${GITHUB_SHA}

      - name: Health Check
        run: |
          for i in {1..30}; do
            if curl --fail http://localhost:8080/health; then
              echo "FinanceHub is healthy."
              exit 0
            fi

            echo "Waiting for FinanceHub..."
            sleep 2
          done

          echo "FinanceHub did not become healthy."
          docker logs financehub-api
          exit 1